name: dartssh2
version: 2.8.2
description: SSH and SFTP client written in pure Dart, aiming to be feature-rich as well as easy to use.
# author is a deprecated pubspec field.
# author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/TerminalStudio/dartssh2

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  asn1lib: ^1.0.0
  convert: ^3.0.0
  meta: ^1.1.6
  pointycastle: ^3.0.0
  pinenacl: ^0.5.0
  socket_io_client: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.1
  dart_code_metrics: ^4.16.0
  lints: ^2.0.0
  test: ^1.6.5

false_secrets:
  - test
